/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forme;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.List;
import javax.swing.JPanel;
import model.Recepcionar;
import server.Server;

/**
 *
 * @author dare2
 */
public class ServerskaForma extends javax.swing.JFrame {

    Server server;
    ModelRecepcionar model;
    List<Recepcionar> logovani = controller.Controller.getInstance().getLogovaniRecepcionari();

    /**
     * Creates new form ServerskaForma
     */
    public ServerskaForma() {
        setContentPane(new GradientPanel());
        initComponents();
        setResizable(false);
        controller.Controller.getInstance().setSf(this);
        jLabelStatus.setText("SERVER JE ISKLJUCEN");
        jLabelStatus.setForeground(Color.red);
        setLocationRelativeTo(null);
        setujModel(logovani);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton = new javax.swing.JButton();
        jLabelStatus = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(200, 220, 255));

        jButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton.setText("ukljuci server");
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        jLabelStatus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStatus.setText("SERVER JE ISKLJUCEN");

        jButton1.setText("KONFIGURACIJA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jButton)))
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabelStatus)
                .addGap(41, 41, 41)
                .addComponent(jButton)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        String naziv = jLabelStatus.getText();
        if (naziv.equals("SERVER JE ISKLJUCEN")) {
            jButton.setText("iskljuci server");
            int port = Integer.parseInt(konfiguracija.Konfiguracija.getInstance().getProperty("port"));
            server = new Server(port);
            server.start();
            jButton.setText("iskljuci server");
            jLabelStatus.setText("SERVER JE UKLJUCEN");
            jLabelStatus.setForeground(Color.green);

        } else {
            jButton.setText("ukljuci server");
            server.ugasiSveKlijente();
            logovani = controller.Controller.getInstance().getLogovaniRecepcionari();
            server.zaustaviServer();
            jLabelStatus.setText(naziv);
            jLabelStatus.setText("SERVER JE ISKLJUCEN");
            jLabelStatus.setForeground(Color.red);

        }
    }//GEN-LAST:event_jButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        KonfiguracijaForma kf = new KonfiguracijaForma(this, true);
        kf.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelStatus;
    // End of variables declaration//GEN-END:variables

    public void setujModel(List<Recepcionar> online) {
        model = new ModelRecepcionar(online);
    }

    class GradientPanel extends JPanel {

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Graphics2D g2d = (Graphics2D) g;
            int width = getWidth();
            int height = getHeight();

            // Boje gradijenta (možeš menjati nijanse po želji)
            Color topColor = new Color(220, 235, 255);   // svetloplava gore
            Color bottomColor = new Color(240, 240, 245); // svetlosiva dole

            GradientPaint gp = new GradientPaint(0, 0, topColor, 0, height, bottomColor);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }
}

